sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

language: java

jdk:
  - oraclejdk8

script: mvn clean verify -P errorprone-compiler


notifications:
  email: 
    - andyglick@gmail.com